# Uncomment this line to define a global platform for your project
platform :ios, '14.0.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      
    end
  end

  bitcode_strip_path = `xcrun --find bitcode_strip`.chop!

  def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
    framework_path = File.join(Dir.pwd, framework_relative_path)
    command = "#{bitcode_strip_path} -r #{framework_path} -o #{framework_path}"
    puts "Stripping bitcode: #{command}"
    system(command)
  end

  framework_paths = [
    "Pods/iZettleSDK/iZettleSDK/iZettlePayments.xcframework/ios-arm64/iZettlePayments.framework/iZettlePayments",
    "Pods/iZettleSDK/iZettleSDK/iZettlePayments.xcframework/ios-arm64_x86_64-simulator/iZettlePayments.framework/iZettlePayments",
    "Pods/iZettleSDK/iZettleSDK/iZettleSDK.xcframework/ios-arm64/iZettleSDK.framework/iZettleSDK",
    "Pods/iZettleSDK/iZettleSDK/iZettleSDK.xcframework/ios-arm64_x86_64-simulator/iZettleSDK.framework/iZettleSDK"
  ]

  framework_paths.each do |path|
    strip_bitcode_from_framework(bitcode_strip_path, path)
  end
end